version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - thatleda

  - package-ecosystem: npm
    directory: /
    rebase-strategy: auto
    schedule:
      interval: daily
    assignees:
      - thatleda
    allow:
      - dependency-type: direct
    versioning-strategy: auto
    groups:
      react:
        patterns:
          - react
          - react-dom
          - react-is
          - '@types/react'
    pull-request-branch-name:
      separator: /
