[[redirects]]
from = "/structure"
to = "/"
status = 200

[Settings]
ID = "6b1b74c8-f3d2-4849-9697-2fd679f40077"

[functions]

[functions."*"]

[build]
publish = "/home/runner/work/vulfden/vulfden/dist"
publishOrigin = "default"
commandOrigin = "ui"
command = "pnpm run build"
