packages:
  - .

catalog:
  '@antfu/eslint-config': 7.4.3
  '@eslint-react/eslint-plugin': ^2.13.0
  '@sanity/icons': 3.7.4
  '@sanity/structure': 2.36.2
  '@sanity/ui': 3.1.11
  '@sanity/vision': 5.12.0
  '@types/react': 19.2.14
  '@types/styled-components': 5.1.36
  eslint: 9.39.2
  eslint-plugin-react-refresh: ^0.5.2
  netlify-cli: 23.15.1
  react: 19.2.4
  react-dom: 19.2.4
  react-is: 19.2.4
  sanity: 5.11.0
  sanity-plugin-media: 4.1.1
  styled-components: 6.3.11
  typescript: 5.9.3

catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - '@netlify/edge-bundler'
  - '@netlify/zip-it-and-ship-it'
  - '@netlify/serverless-functions-api'
  - '@netlify/images'
  - react-redux@9.2.0
  - '@reduxjs/toolkit@2.11.0'
  - pino@9.14.0
  - reselect@5.1.1
  - groq@3.88.1-typegen-experimental.0
  - semver
  - undici
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@octokit/endpoint@9.0.6'
