catalog:
  '@antfu/eslint-config': 6.7.3
  '@sanity/icons': 3.7.4
  '@sanity/structure': 2.36.2
  '@sanity/ui': 3.1.11
  '@sanity/vision': 5.2.0
  '@types/react': 19.2.7
  '@types/styled-components': 5.1.36
  eslint: 9.39.2
  netlify-cli: 23.13.0
  react: 19.2.3
  react-dom: 19.2.3
  react-is: 19.2.3
  sanity: 5.2.0
  sanity-plugin-media: 4.1.1
  styled-components: 6.1.19
  typescript: 5.9.3

catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
