catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade

catalog:
  '@antfu/eslint-config': 6.4.2
  '@eslint-react/eslint-plugin': 2.3.13
  '@sanity/eslint-config-studio': 5.0.2
  '@sanity/icons': 3.7.4
  '@sanity/structure': 2.36.2
  '@sanity/ui': 3.1.11
  '@sanity/vision': 4.20.3
  '@types/react': 19.2.7
  '@types/styled-components': 5.1.36
  eslint: 9.39.1
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.24
  netlify-cli: 23.12.3
  prettier: 3.7.4
  react: 19.2.1
  react-dom: 19.2.1
  react-is: 19.2.1
  sanity: 4.20.3
  sanity-plugin-media: 4.1.0
  styled-components: 6.1.19
  typescript: 5.9.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram
  - unrs-resolver
