packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  netlify-cli: true

catalog:
  '@antfu/eslint-config': 8.2.0
  '@eslint-react/eslint-plugin': 5.7.6
  '@sanity/document-internationalization': 6.1.1
  '@sanity/icons': 3.7.4
  '@sanity/structure': 2.36.2
  '@sanity/ui': 3.2.0
  '@sanity/vision': 5.24.0
  '@types/react': 19.2.14
  '@types/styled-components': 5.1.36
  eslint: 10.3.0
  eslint-plugin-react-refresh: ^0.5.2
  netlify-cli: 26.0.1
  react: 19.2.5
  react-dom: 19.2.5
  react-is: 19.2.5
  sanity: 5.24.0
  sanity-plugin-media: 4.2.0
  styled-components: 6.4.1
  typescript: 5.9.3
overrides:
  '@fastify/static': '>=9.1.1'
  brace-expansion: '>=2.0.3'
  js-yaml: '>=3.14.2'
  minimatch: '>=9.0.6'
  path-to-regexp: '>=8.4.0'
  uuid: '>=13.0.1'

shellEmulator: true
trustPolicy: no-downgrade
