packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true

catalog:
  '@antfu/eslint-config': 9.0.0
  '@eslint-react/eslint-plugin': 5.8.12
  '@sanity/document-internationalization': 6.2.1
  '@sanity/icons': 3.7.4
  '@sanity/structure': 2.36.2
  '@sanity/ui': 3.2.0
  '@sanity/vision': 5.28.0
  '@types/react': 19.2.15
  '@types/styled-components': 5.1.36
  eslint: 10.4.1
  eslint-plugin-react-refresh: ^0.5.2
  netlify-cli: 26.0.2
  react: 19.2.6
  react-dom: 19.2.6
  react-is: 19.2.6
  sanity: 5.30.0
  sanity-plugin-media: 4.3.0
  styled-components: 6.4.2
  typescript: 6.0.3
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.8.1'
  - '@eslint-react/core@5.8.1'
  - '@eslint-react/eslint-plugin@5.8.1'
  - '@eslint-react/eslint@5.8.1'
  - '@eslint-react/jsx@5.8.1'
  - '@eslint-react/shared@5.8.1'
  - '@eslint-react/var@5.8.1'
  - eslint-plugin-react-dom@5.8.1
  - eslint-plugin-react-jsx@5.8.1
  - eslint-plugin-react-naming-convention@5.8.1
  - eslint-plugin-react-rsc@5.8.1
  - eslint-plugin-react-web-api@5.8.1
  - eslint-plugin-react-x@5.8.1
overrides:
  '@fastify/static': '>=9.1.1'
  brace-expansion: '>=2.0.3'
  js-yaml: '>=3.14.2'
  minimatch: '>=9.0.6'
  path-to-regexp: '>=8.4.0'
  uuid: '>=13.0.1'
  tmp: ">=0.2.6"

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - '@netlify/*'
  - chokidar
  - groq
  - semver
