name: Pull Request CI

on: pull_request

jobs:
  preview:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      SANITY_STUDIO_PROJECT_ID: brvct6ie
      SANITY_STUDIO_DATASET: production
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.10.0
          cache: pnpm
      - name: Run install
        run: pnpm install --shamefully-hoist
      - name: Build production bundle
        run: pnpm build
      - name: Lint files
        run: pnpm lint:ci
