name: Pull Request CI

on: pull_request

jobs:
  preview:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      SANITY_STUDIO_PROJECT_ID: brvct6ie
      SANITY_STUDIO_DATASET: production
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Run install
        run: bun install
      - name: Build production bundle
        run: bun run build
      - name: Lint files
        run: bun run lint:ci
