name: Release CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SANITY_STUDIO_PROJECT_ID: brvct6ie
      SANITY_STUDIO_DATASET: production
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: pnpm-lock.yaml
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Run install
        run: pnpm install
      - name: Build production bundle
        run: pnpm run build
      - name: Deploy to production
        run: pnpm run deploy --dir ./dist --prod --site ${{secrets.NETLIFY_SITE_ID}} --auth ${{secrets.NETLIFY_TOKEN}}
