name: Release CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SANITY_STUDIO_PROJECT_ID: brvct6ie
      SANITY_STUDIO_DATASET: production
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Run install
        run: bun install
      - name: Build production bundle
        run: bun run build
      - name: Deploy to production
        run: bun run deploy --dir ./dist --prod --site ${{secrets.NETLIFY_SITE_ID}} --auth ${{secrets.NETLIFY_TOKEN}}
